services:
  app-dev:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src/:/usr/src/app/src
    ports:
      - 5173:5173
    container_name: todo-frontend-dev